version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: composer
    directory: /
    ignore:
      - dependency-name: "symfony/*"
        update-types: ["version-update:semver-patch"]
    schedule:
      interval: daily
    open-pull-requests-limit: 15
