version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      actions:
        patterns: *

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
    groups:
      symfony:
        patterns:
          - "symfony/*"
      twig:
        patterns:
          - "twig/*"
