# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(string:APP_SECRET)%'
    csrf_protection:
        enabled: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        name: session
        cookie_secure: auto
        cookie_samesite: strict

    # Trust the DigitalOcean reverse proxy.
    trusted_proxies: '10.0.0.0/8'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port']

    php_errors:
        log: true

    http_client:
        default_options:
            max_duration: '%env(float:HTTP_CLIENT_TIMEOUT)%'
            max_redirects: '%env(int:HTTP_CLIENT_MAX_REDIRECTS)%'
            headers: { 'User-Agent': 'Is is up? (+https://isitup.org)' }
