twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        carbon_ads:
            id: '%env(string:CARBON_ADS_ID)%'
            placement: '%env(string:CARBON_ADS_PLACEMENT)%'

when@test:
    twig:
        strict_variables: true
