twig:
    file_name_pattern: '*.twig'

    globals:
        carbon_ads:
            id: '%env(string:CARBON_ADS_ID)%'
            placement: '%env(string:CARBON_ADS_PLACEMENT)%'

when@test:
    twig:
        strict_variables: true
