apiVersion: apps/v1
kind: Deployment
metadata:
  name: isitup-org
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: isitup-org
      app.kubernetes.io/part-of: isitup-org
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: isitup-org
        app.kubernetes.io/part-of: isitup-org
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - isitup-org
                topologyKey: kubernetes.io/hostname
      containers:
        - name: isitup-org
          image: ghcr.io/sjparkinson/isitup.org:latest
          command: [ "/cnb/lifecycle/launcher"]
          args: ["vendor/bin/heroku-php-apache2", "-p", "80", "public"]
          env:
            - name: APP_ENV
              value: prod
            - name: HTTP_CLIENT_TIMEOUT
              value: "3"
            - name: GOOGLE_ANALYTICS_ID
              value: G-NP4RFP7BZ0
            - name: CARBON_ADS_ID
              value: CKYI5K3I
            - name: CARBON_ADS_PLACEMENT
              value: isituporg
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 20m
              memory: 40Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            timeoutSeconds: 3
      imagePullSecrets:
        - name: github-container-registry
