apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - autoscaling.yaml
  - deployment.yaml
  - ingress.yaml
  - pod-disruption-budget.yaml
  - service.yaml
commonLabels:
  app.kubernetes.io/name: isitup-org
  app.kubernetes.io/part-of: isitup-org
