apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: isitup-org-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: isitup-org
      app.kubernetes.io/part-of: isitup-org