name: Deploy

on:
  workflow_run:
    workflows:
      - Test
    branches:
      - main
    types: 
      - completed

jobs:
  deploy:
    name: Deploy
    environment:
      name: production
      url: https://isitup.org
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Create Apps Platform deployment
        id: deployment
        run: |
          doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }} --force-rebuild --wait
          echo ::set-output name=deployment_id::$(doctl apps list-deployments ${{ secrets.DIGITALOCEAN_APP_ID }} --format ID | sed -n 2p)
          sleep 15

      - name: Get build logs
        if: ${{ always() }}
        run: doctl apps logs ${{ secrets.DIGITALOCEAN_APP_ID }} --type build --deployment ${{ steps.deployment.outputs.deployment_id }}
