name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1

      - name: docker build
        run: |
          docker build . \
            -t docker.pkg.github.com/${{ github.repository }}/isitup.org:latest \
            -t docker.pkg.github.com/${{ github.repository }}/isitup.org:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1

      - name: github deployment
        id: deployment
        uses: chrnorm/deployment-action@releases/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: production

      - name: docker login
        run: docker login docker.pkg.github.com --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: docker build
        run: |
          docker build . \
            -t docker.pkg.github.com/${{ github.repository }}/isitup.org:latest \
            -t docker.pkg.github.com/${{ github.repository }}/isitup.org:${{ github.sha }}

      - name: docker push
        run: |
          docker push docker.pkg.github.com/${{ github.repository }}/isitup.org:latest
          docker push docker.pkg.github.com/${{ github.repository }}/isitup.org:${{ github.sha }}

      - name: doctl kubernetes
        uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show k8s-lon1 > $GITHUB_WORKSPACE/.kubeconfig

      - name: kustomize
        run: |
          cat <<EOF > k8s/kustomization.yaml
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          resources:
            - autoscaling.yaml
            - deployment.yaml
            - ingress.yaml
            - service.yaml
          patchesStrategicMerge:
            - image.yaml
          EOF

          cat <<EOF > k8s/image.yaml
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: isitup-org
          spec:
            template:
              spec:
                containers:
                  - name: isitup-org
                    image: docker.pkg.github.com/${{ github.repository }}/isitup.org:${{ github.sha }}
          EOF

      - name: kubectl apply
        run: kubectl --kubeconfig $GITHUB_WORKSPACE/.kubeconfig apply -k k8s/

      - name: kubectl rollout status
        run: kubectl --kubeconfig $GITHUB_WORKSPACE/.kubeconfig rollout status deployment/isitup-org

      - name: github deployment success
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: success
          target-url: https://isitup.org
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: github deployment failure
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: failure
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}