name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1

      - name: docker build
        run: |
          docker build . \
            -t docker.pkg.github.com/${{ github.repository }}/isitup.org:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1

      - name: github deployment
        id: deployment
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ github.token }}
          script: |
            const deployment = await github.repos.createDeployment({
              ...context.repo,
              ref: '${{ github.sha }}',
              environment: 'production',
              required_contexts: [],
              mediaType: { previews: ['flash', 'ant-man'] }
            })

            return deployment.data.id;

      - name: github deployment in progress
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ github.token }}
          script: |
            github.repos.createDeploymentStatus({
              ...context.repo,
              deployment_id: ${{ steps.deployment.outputs.result }},
              state: 'in_progress',
              log_url: 'https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks',
              mediaType: { previews: ['flash', 'ant-man'] }
            })

      - name: docker login
        run: docker login docker.pkg.github.com --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: docker build
        run: |
          docker build . \
            -t docker.pkg.github.com/${{ github.repository }}/isitup.org:${{ github.sha }} \
            -t docker.pkg.github.com/${{ github.repository }}/isitup.org:latest

      - name: docker push
        run: |
          docker push docker.pkg.github.com/${{ github.repository }}/isitup.org:${{ github.sha }}
          docker push docker.pkg.github.com/${{ github.repository }}/isitup.org:latest

      - name: doctl kubernetes
        uses: digitalocean/action-doctl@master
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show k8s-lon1 > $GITHUB_WORKSPACE/.kubeconfig

      - name: kustomize
        run: |
          cat <<EOF > k8s/kustomization.yaml
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          resources:
            - autoscaling.yaml
            - deployment.yaml
            - ingress.yaml
            - service.yaml
          patchesStrategicMerge:
            - image.yaml
          EOF

          cat <<EOF > k8s/image.yaml
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: isitup-org
          spec:
            template:
              spec:
                containers:
                  - name: isitup-org
                    image: docker.pkg.github.com/${{ github.repository }}/isitup.org:${{ github.sha }}
          EOF

      - name: kubectl apply
        run: kubectl --kubeconfig $GITHUB_WORKSPACE/.kubeconfig apply -k k8s/

      - name: kubectl rollout status
        run: kubectl --kubeconfig $GITHUB_WORKSPACE/.kubeconfig rollout status deployment/isitup-org

      - name: github deployment success
        uses: actions/github-script@0.3.0
        if: success()
        with:
          github-token: ${{ github.token }}
          script: |
            github.repos.createDeploymentStatus({
              ...context.repo,
              deployment_id: ${{ steps.deployment.outputs.result }},
              state: 'success',
              environment_url: 'https://isitup.org',
              auto_inactive: true,
              log_url: 'https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks',
              mediaType: { previews: ['flash', 'ant-man'] }
            })

      - name: github deployment failure
        uses: actions/github-script@0.3.0
        if: failure()
        with:
          github-token: ${{ github.token }}
          script: |
            github.repos.createDeploymentStatus({
              ...context.repo,
              deployment_id: ${{ steps.deployment.outputs.result }},
              state: 'failure',
              log_url: 'https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks',
              mediaType: { previews: ['flash', 'ant-man'] }
            })
