name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: docker build
        run: docker build -t docker.pkg.github.com/${{ github.repository }}/isitup.org:latest .

      - name: docker login
        if: github.ref == 'refs/heads/master'
        run: docker login docker.pkg.github.com --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: docker push
        if: github.ref == 'refs/heads/master'
        run: docker push docker.pkg.github.com/${{ github.repository }}/isitup.org:latest

      - name: github deployment
        if: github.ref == 'refs/heads/master'
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ github.token }}
          script: |
            github.repos.createDeployment({
              ...context.repo,
              ref: 'master',
              environment: 'production',
              required_contexts: [],
              payload: {
                image: 'docker.pkg.github.com/${{ github.repository }}/isitup.org:latest'
              }
            })
