name: PHP

on:
  - push
  - pull_request

permissions: read-all

env:
  php-version: '8.2'
  php-extensions: ctype, curl, iconv, intl, json, pcre, session, simplexml, tokenizer

jobs: 
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
        with:
          persist-credentials: false

      - name: Setup PHP, with Composer and extensions
        uses: shivammathur/setup-php@d30ad8b1843ace22e6698ab99bbafaa747b6bd0d
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.php-extensions }}

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer packages
        uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - run: composer validate --strict --ansi
      
      - name: Install Composer packages
        run: composer install --no-progress --ansi

      - run: composer test --ansi

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
        with:
          persist-credentials: false

      - name: Setup PHP with Composer and extensions
        uses: shivammathur/setup-php@d30ad8b1843ace22e6698ab99bbafaa747b6bd0d
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.php-extensions }}

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer packages
        uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
            $HOME/.cache/psalm
          key: ${{ runner.os }}-psalm-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-psalm-

      - run: composer install --no-progress --ansi

      - name: Run Psalm
        run: php vendor/bin/psalm --output-format=github --long-progress

  deploy:
    name: Deploy
    environment:
      name: production
      url: https://isitup.org
    concurrency: production
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs:
      - phpunit
      - psalm
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@ba7726ed64a9c5eb774152b1ea03bf67ee81ad6e
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Create Apps Platform deployment
        id: deployment
        run: doctl apps create-deployment 7172ee3c-69f7-40cf-9bb4-ee712bbc7871 --force-rebuild --wait

      - name: Get build logs
        if: ${{ always() }}
        run: doctl apps logs 7172ee3c-69f7-40cf-9bb4-ee712bbc7871 --type build
