name: PHP

on:
  - push
  - pull_request

permissions: read-all

env:
  php-version: '8.2'
  php-extensions: ctype, curl, iconv, intl, json, pcre, session, simplexml, tokenizer

jobs: 
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          persist-credentials: false

      - name: Setup PHP, with Composer and extensions
        uses: shivammathur/setup-php@4bd44f22a98a19e0950cbad5f31095157cc9621b
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.php-extensions }}

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer packages
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - run: composer validate --strict --ansi
      
      - name: Install Composer packages
        run: composer install --no-progress --ansi

      - run: composer test --ansi

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          persist-credentials: false

      - name: Setup PHP with Composer and extensions
        uses: shivammathur/setup-php@4bd44f22a98a19e0950cbad5f31095157cc9621b
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.php-extensions }}

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer packages
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
            $HOME/.cache/psalm
          key: ${{ runner.os }}-psalm-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-psalm-

      - run: composer install --no-progress --ansi

      - name: Run Psalm
        run: php vendor/bin/psalm --output-format=github --long-progress

  deploy:
    name: Deploy
    environment:
      name: production
      url: https://isitup.org
    concurrency: production
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs:
      - phpunit
      - psalm
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@595d91dabf2c6f9194ba08393311cba86e45b6ae
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Create Apps Platform deployment
        id: deployment
        run: doctl apps create-deployment 7172ee3c-69f7-40cf-9bb4-ee712bbc7871 --force-rebuild --wait

      - name: Get build logs
        if: ${{ always() }}
        run: doctl apps logs 7172ee3c-69f7-40cf-9bb4-ee712bbc7871 --type build
