name: Security

on:
  - push
  - pull_request

permissions: read-all

env:
  php-version: '8.2'
  php-extensions: ctype, curl, iconv, intl, json, pcre, session, simplexml, tokenizer

jobs:
  dependencies:
    name: Dependency Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          persist-credentials: false

      - uses: actions/dependency-review-action@c090f4e553673e6e505ea70d6a95362ee12adb94

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          persist-credentials: false

      - name: Setup PHP with Composer and extensions
        uses: shivammathur/setup-php@d30ad8b1843ace22e6698ab99bbafaa747b6bd0d
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.php-extensions }}

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer packages
        uses: actions/cache@6998d139ddd3e68c71e9e398d8e40b71a2f39812
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
            $HOME/.cache/psalm
          key: ${{ runner.os }}-security-psalm-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-security-psalm-

      - run: composer install --no-progress --ansi

      - name: Run Psalm security analysis
        run: php vendor/bin/psalm --taint-analysis --output-format=github --long-progress --report=psalm-results.sarif

      - name: Upload Psalm security analysis to GitHub
        uses: github/codeql-action/upload-sarif@17573ee1cc1b9d061760f3a006fc4aac4f944fd5
        with:
          sarif_file: psalm-results.sarif
