name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: read-all

env:
  php-version: '8.0'
  php-extensions: ctype, curl, iconv, intl, json, pcre, session, simplexml, tokenizer

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          persist-credentials: false

      - name: Setup PHP with Composer and extensions
        uses: shivammathur/setup-php@7854a0cae7fa7a5f3feac66d27bae2dc42d1067a
        with:
          php-version: ${{ env.php-version }}
          extensions: ${{ env.php-extensions }}

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer packages
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
            $HOME/.cache/psalm
          key: ${{ runner.os }}-security-psalm-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-security-psalm-

      - run: composer install --no-progress --ansi

      - name: Run Psalm security analysis
        run: php vendor/bin/psalm --taint-analysis --output-format=github --long-progress --report=psalm-results.sarif

      - name: Upload Psalm security analysis to GitHub
        uses: github/codeql-action/upload-sarif@ec300a3159b7f1c667253f7555e4a2dca734a537
        with:
          sarif_file: psalm-results.sarif
