name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP, with Composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: ctype, curl, iconv

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - run: composer validate

      - name: Cache Composer packages
        uses: actions/cache@v2.1.4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Cache PHPUnit runtime
        uses: actions/cache@v2.1.4
        with:
          path: bin/.phpunit
          key: ${{ runner.os }}-phpunit-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-phpunit-
      - run: composer validate --strict
      
      - run: composer install --no-progress

      - run: composer test
